services:
  db:
    image: mysql:8.0
    container_name: vollmed_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed
      MYSQL_USER: api
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always