version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vollmed_api_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: api
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"